# 통합실행 docker-compose
version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    container_name: frontend_app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - dokidoki-network
    ports:
      - "3030:3030"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql_data:

networks:
  dokidoki-network:
