services:
  frontend:
    build:
      context: ./practice-front
      target: build
    ports:
      - "5173:5173"
    volumes:
      - ./practice-front:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - dokidoki-network
    environment:
      - VITE_DEV_MODE=true

networks:
  dokidoki-network:
