version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      target: build
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - dokidoki-network
    environment:
      - VITE_DEV_MODE=true

  # backend:

networks:
  dokidoki-network: